from wstore.offerings.offering_tests import *
from wstore.offerings.resource_tests import *
from wstore.admin.markets.tests import *
from wstore.admin.repositories.tests import *
from wstore.contracting.tests import *
from wstore.search.tests import *
from wstore.charging_engine.tests import *
from wstore.store_commons.tests import *
from wstore.market_adaptor.tests import *
